import { createHash, randomUUID } from "node:crypto";
import { copyFile, mkdir, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { basename, dirname, extname, join } from "node:path";
import type { BrowserWindow } from "electron";
import { activeTypographySystem, faceForCandidate, sourceForCandidate, type StudyDocument } from "../src/domain.js";
import { csvCell, safeFileStem } from "./host-storage.js";

interface HandoffOptions {
  readonly window: BrowserWindow;
  readonly document: StudyDocument;
  readonly targetDirectory: string;
  readonly sourcePaths: ReadonlyMap<string, string>;
  readonly includeSources: boolean;
  readonly sourcePermissionAcknowledged: boolean;
}

interface ManifestEntry {
  readonly path: string;
  readonly bytes: number;
  readonly sha256: string;
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function sha256(path: string): Promise<string> {
  return createHash("sha256").update(await readFile(path)).digest("hex");
}

function summary(document: StudyDocument): string {
  const system = activeTypographySystem(document);
  const decisionCounts = Object.fromEntries(["unreviewed", "keep", "maybe", "reject"].map((state) => [state, document.candidates.filter((candidate) => candidate.reviewState === state).length]));
  const roles = system.fontUses.map((use) => {
    const candidate = use.originatingCandidateId
      ? document.candidates.find((item) => item.id === use.originatingCandidateId)
      : undefined;
    const face = document.faces.find((item) => item.id === use.faceId);
    return `| ${use.role} | ${face?.family ?? "Missing Face"} | ${candidate?.label ?? "Independent Font Use"} | ${use.rationale || "—"} |`;
  });
  return `# ${document.title}\n\nGenerated by Font Previewer. This Handoff records typography decisions; it does not grant font redistribution rights.\n\n## Decision status\n\n- Keep: ${decisionCounts.keep}\n- Maybe: ${decisionCounts.maybe}\n- Reject: ${decisionCounts.reject}\n- Unreviewed: ${decisionCounts.unreviewed}\n\n## Typography System — ${system.name}\n\n| Role | Family | Candidate | Rationale |\n| --- | --- | --- | --- |\n${roles.join("\n") || "| — | — | — | No Roles assigned |"}\n\n## Sources\n\n${document.sources.map((source) => `- ${source.displayName} — ${source.hint.format}; last known ${source.lastKnownState}`).join("\n") || "No Sources recorded."}\n`;
}

function candidateCsv(document: StudyDocument): string {
  const rows = [["candidate_id", "family", "style", "label", "review_state", "axes", "features", "tags", "notes", "rationale"]];
  for (const candidate of document.candidates) {
    const face = faceForCandidate(document, candidate);
    rows.push([
      candidate.id,
      face.family,
      face.style,
      candidate.label,
      candidate.reviewState,
      candidate.axes.map((axis) => `${axis.tag}=${axis.value}`).join(";"),
      candidate.features.map((feature) => `${feature.tag}=${feature.enabled ? 1 : 0}`).join(";"),
      candidate.tags.join(";"),
      candidate.notes,
      candidate.rationale,
    ]);
  }
  return `${rows.map((row) => row.map(csvCell).join(",")).join("\n")}\n`;
}

async function captureStage(window: BrowserWindow, stage: "Review" | "Compare" | "System", path: string): Promise<void> {
  await window.webContents.executeJavaScript(`(() => {
    const button = [...document.querySelectorAll('.stage-nav button')].find((item) => item.textContent?.includes(${JSON.stringify(stage)}));
    if (!(button instanceof HTMLButtonElement)) throw new Error('Missing ${stage} stage');
    button.click();
  })()`, true);
  await new Promise((resolve) => setTimeout(resolve, 120));
  const image = await window.webContents.capturePage();
  await writeFile(path, image.toPNG(), { mode: 0o600 });
}

async function uniqueFinalPath(targetDirectory: string, requestedStem: string): Promise<string> {
  for (let suffix = 0; suffix < 1_000; suffix += 1) {
    const name = suffix === 0 ? `${requestedStem} Handoff` : `${requestedStem} Handoff ${suffix + 1}`;
    const candidate = join(targetDirectory, name);
    if (!(await exists(candidate))) return candidate;
  }
  throw new Error("Could not choose a unique Handoff folder name.");
}

export async function exportTransactionalHandoff(options: HandoffOptions): Promise<{ readonly displayName: string; readonly fileCount: number }> {
  if (options.includeSources && !options.sourcePermissionAcknowledged) {
    throw new Error("Source-copy permission was not acknowledged.");
  }
  const requestedStem = safeFileStem(options.document.title, "Font Previewer");
  const finalPath = await uniqueFinalPath(options.targetDirectory, requestedStem);
  const stagingPath = join(options.targetDirectory, `.${basename(finalPath)}.staging-${randomUUID()}`);
  if (dirname(stagingPath) !== options.targetDirectory || !basename(stagingPath).includes(".staging-")) {
    throw new Error("Invalid Handoff staging path.");
  }
  await mkdir(stagingPath, { recursive: false, mode: 0o700 });
  try {
    const outputs = new Set(options.document.handoff.outputs);
    if (outputs.has("json")) await writeFile(join(stagingPath, "study.pitchfontstudy"), `${JSON.stringify(options.document, null, 2)}\n`, { mode: 0o600 });
    if (outputs.has("summary")) await writeFile(join(stagingPath, "README.md"), summary(options.document), { mode: 0o600 });
    if (outputs.has("csv")) await writeFile(join(stagingPath, "candidates.csv"), candidateCsv(options.document), { mode: 0o600 });

    const activeStage = await options.window.webContents.executeJavaScript(`document.querySelector('.stage-nav [aria-current="step"]')?.textContent ?? 'Handoff'`, true) as string;
    if (outputs.has("review-png")) await captureStage(options.window, "Review", join(stagingPath, "review.png"));
    if (outputs.has("compare-png")) await captureStage(options.window, "Compare", join(stagingPath, "compare.png"));
    if (outputs.has("system-png")) await captureStage(options.window, "System", join(stagingPath, "system.png"));
    if (outputs.has("pdf")) {
      const pdf = await options.window.webContents.printToPDF({ printBackground: true, pageSize: "A4", landscape: true });
      await writeFile(join(stagingPath, "study.pdf"), pdf, { mode: 0o600 });
    }
    const originalStage = ["Review", "Compare", "System", "Handoff"].find((stage) => activeStage.includes(stage));
    if (originalStage) {
      await options.window.webContents.executeJavaScript(`([...document.querySelectorAll('.stage-nav button')].find((item) => item.textContent?.includes(${JSON.stringify(originalStage)})))?.click()`, true);
    }

    if (options.includeSources) {
      const sourcesDirectory = join(stagingPath, "Sources");
      await mkdir(sourcesDirectory, { mode: 0o700 });
      const usedNames = new Set<string>();
      for (const source of options.document.sources) {
        const sourcePath = options.sourcePaths.get(source.id);
        if (!sourcePath) continue;
        const extension = extname(sourcePath);
        const base = safeFileStem(source.displayName, "Source");
        let name = `${base}${extension}`;
        for (let suffix = 2; usedNames.has(name.toLocaleLowerCase()); suffix += 1) name = `${base} ${suffix}${extension}`;
        usedNames.add(name.toLocaleLowerCase());
        await copyFile(sourcePath, join(sourcesDirectory, name));
      }
    }

    const relativeFiles = (await readdir(stagingPath, { recursive: true, withFileTypes: true }))
      .filter((entry) => entry.isFile())
      .map((entry) => join(entry.parentPath.slice(stagingPath.length + 1), entry.name))
      .sort();
    const entries: ManifestEntry[] = [];
    for (const relativePath of relativeFiles) {
      const path = join(stagingPath, relativePath);
      const metadata = await stat(path);
      if (!metadata.isFile() || metadata.size === 0) throw new Error(`Handoff output is empty: ${relativePath}`);
      entries.push({ path: relativePath, bytes: metadata.size, sha256: await sha256(path) });
    }
    const manifest = {
      manifestVersion: 1,
      generatedAt: new Date().toISOString(),
      product: "Font Previewer",
      studyId: options.document.id,
      schemaVersion: options.document.schemaVersion,
      sourcesIncluded: options.includeSources,
      redistributionPermissionAcknowledged: options.includeSources && options.sourcePermissionAcknowledged,
      files: entries,
    };
    await writeFile(join(stagingPath, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, { mode: 0o600 });
    await writeFile(join(stagingPath, "checksums.sha256"), `${entries.map((entry) => `${entry.sha256}  ${entry.path}`).join("\n")}\n`, { mode: 0o600 });
    for (const entry of entries) {
      if (await sha256(join(stagingPath, entry.path)) !== entry.sha256) throw new Error(`Handoff verification failed: ${entry.path}`);
    }
    await rename(stagingPath, finalPath);
    return { displayName: basename(finalPath), fileCount: entries.length + 2 };
  } catch (error) {
    await rm(stagingPath, { recursive: true, force: true });
    throw error;
  }
}
